/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test.auto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Алексей
 */
public class new_order extends javax.swing.JFrame {
Connection conn = null;
ResultSet rs = null;

PreparedStatement pst = null;


public static String  temp;
static  Integer box;
    /**
     * Creates new form new_order
     */
    public new_order() {
        initComponents();
                 conn = javaconnect.ConnecrDb();
              
                 loadBoxes();
set_from();
     _setBusy();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jXTitledPanel3 = new org.jdesktop.swingx.JXTitledPanel();
        jXBusyLabel10 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel7 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel11 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel8 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel12 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel9 = new org.jdesktop.swingx.JXLabel();
        jXButton8 = new org.jdesktop.swingx.JXButton();
        jXTitledPanel6 = new org.jdesktop.swingx.JXTitledPanel();
        jXBusyLabel19 = new org.jdesktop.swingx.JXBusyLabel();
        jXBusyLabel20 = new org.jdesktop.swingx.JXBusyLabel();
        jXBusyLabel21 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel22 = new org.jdesktop.swingx.JXLabel();
        jXLabel24 = new org.jdesktop.swingx.JXLabel();
        jXLabel23 = new org.jdesktop.swingx.JXLabel();
        jXButton6 = new org.jdesktop.swingx.JXButton();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jXBusyLabel1 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel2 = new org.jdesktop.swingx.JXBusyLabel();
        jXBusyLabel3 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel3 = new org.jdesktop.swingx.JXLabel();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        jXTitledPanel4 = new org.jdesktop.swingx.JXTitledPanel();
        jXBusyLabel13 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel10 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel14 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel11 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel15 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel12 = new org.jdesktop.swingx.JXLabel();
        jXButton7 = new org.jdesktop.swingx.JXButton();
        jXTitledPanel2 = new org.jdesktop.swingx.JXTitledPanel();
        jXBusyLabel9 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel4 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel8 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel6 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel7 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel5 = new org.jdesktop.swingx.JXLabel();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXList1 = new org.jdesktop.swingx.JXList();
        jXTitledPanel8 = new org.jdesktop.swingx.JXTitledPanel();
        jXBusyLabel25 = new org.jdesktop.swingx.JXBusyLabel();
        jXBusyLabel26 = new org.jdesktop.swingx.JXBusyLabel();
        jXBusyLabel27 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel16 = new org.jdesktop.swingx.JXLabel();
        jXLabel18 = new org.jdesktop.swingx.JXLabel();
        jXLabel17 = new org.jdesktop.swingx.JXLabel();
        jXButton9 = new org.jdesktop.swingx.JXButton();
        jXTitledPanel7 = new org.jdesktop.swingx.JXTitledPanel();
        jXBusyLabel22 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel19 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel23 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel20 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel24 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel21 = new org.jdesktop.swingx.JXLabel();
        jXButton10 = new org.jdesktop.swingx.JXButton();
        jXTitledPanel5 = new org.jdesktop.swingx.JXTitledPanel();
        jXBusyLabel16 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel13 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel17 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel14 = new org.jdesktop.swingx.JXLabel();
        jXBusyLabel18 = new org.jdesktop.swingx.JXBusyLabel();
        jXLabel15 = new org.jdesktop.swingx.JXLabel();
        jXButton5 = new org.jdesktop.swingx.JXButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jXTitledPanel3.setOpaque(true);
        jXTitledPanel3.setTitle(" Бокс 7");
        jXTitledPanel3.setTitleFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jXBusyLabel10.setBusy(true);
        jXBusyLabel10.setText("Сумма");

        jXLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel7.setText("Пусто");

        jXBusyLabel11.setBusy(true);
        jXBusyLabel11.setText("Класс автомобиля");

        jXLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel8.setText("Пусто");

        jXBusyLabel12.setBusy(true);
        jXBusyLabel12.setText("Номер автомобиля");

        jXLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel9.setText("Пусто");

        jXButton8.setText("Оплатить/Сделать заказ");
        jXButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel3Layout = new javax.swing.GroupLayout(jXTitledPanel3.getContentContainer());
        jXTitledPanel3.getContentContainer().setLayout(jXTitledPanel3Layout);
        jXTitledPanel3Layout.setHorizontalGroup(
            jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXBusyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTitledPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jXTitledPanel3Layout.setVerticalGroup(
            jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jXButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jXTitledPanel6.setOpaque(true);
        jXTitledPanel6.setTitle(" Бокс 8");
        jXTitledPanel6.setTitleFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jXBusyLabel19.setBusy(true);
        jXBusyLabel19.setText("Сумма");

        jXBusyLabel20.setBusy(true);
        jXBusyLabel20.setText("Класс автомобиля");

        jXBusyLabel21.setBusy(true);
        jXBusyLabel21.setText("Номер автомобиля");

        jXLabel22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel22.setText("Пусто");

        jXLabel24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel24.setText("Пусто");

        jXLabel23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel23.setText("Пусто");

        jXButton6.setText("Оплатить/Сделать заказ");
        jXButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel6Layout = new javax.swing.GroupLayout(jXTitledPanel6.getContentContainer());
        jXTitledPanel6.getContentContainer().setLayout(jXTitledPanel6Layout);
        jXTitledPanel6Layout.setHorizontalGroup(
            jXTitledPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXBusyLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTitledPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jXTitledPanel6Layout.setVerticalGroup(
            jXTitledPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTitledPanel6Layout.createSequentialGroup()
                        .addComponent(jXBusyLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXBusyLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXBusyLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXTitledPanel6Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jXLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jXLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jXLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jXTitledPanel1.setOpaque(true);
        jXTitledPanel1.setTitle("Бокс 1");
        jXTitledPanel1.setTitleFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jXTitledPanel1.setToolTipText("");

        jXBusyLabel1.setBusy(true);
        jXBusyLabel1.setText("Номер автомобиля");

        jXLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel1.setText("Пусто");

        jXLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel2.setText("Пусто");

        jXBusyLabel2.setBusy(true);
        jXBusyLabel2.setText("Класс автомобиля");

        jXBusyLabel3.setBusy(true);
        jXBusyLabel3.setText("Сумма");

        jXLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel3.setText("Пусто");

        jXButton1.setText("Оплатить/Сделать заказ");
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXBusyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jXLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jXLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXTitledPanel4.setOpaque(true);
        jXTitledPanel4.setTitle(" Бокс 4");
        jXTitledPanel4.setTitleFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jXBusyLabel13.setBusy(true);
        jXBusyLabel13.setText("Сумма");

        jXLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel10.setText("Пусто");

        jXBusyLabel14.setBusy(true);
        jXBusyLabel14.setText("Класс автомобиля");

        jXLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel11.setText("Пусто");

        jXBusyLabel15.setBusy(true);
        jXBusyLabel15.setText("Номер автомобиля");

        jXLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel12.setText("Пусто");

        jXButton7.setText("Оплатить/Сделать заказ");
        jXButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel4Layout = new javax.swing.GroupLayout(jXTitledPanel4.getContentContainer());
        jXTitledPanel4.getContentContainer().setLayout(jXTitledPanel4Layout);
        jXTitledPanel4Layout.setHorizontalGroup(
            jXTitledPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXBusyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXTitledPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jXTitledPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jXButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXTitledPanel4Layout.setVerticalGroup(
            jXTitledPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jXButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jXTitledPanel2.setOpaque(true);
        jXTitledPanel2.setTitle(" Бокс 2");
        jXTitledPanel2.setTitleFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jXBusyLabel9.setBusy(true);
        jXBusyLabel9.setText("Сумма");

        jXLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel4.setText("Пусто");

        jXBusyLabel8.setBusy(true);
        jXBusyLabel8.setText("Класс автомобиля");

        jXLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel6.setText("Пусто");

        jXBusyLabel7.setBusy(true);
        jXBusyLabel7.setText("Номер автомобиля");

        jXLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel5.setText("Пусто");

        jXButton2.setText("Оплатить/Сделать заказ");
        jXButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel2Layout = new javax.swing.GroupLayout(jXTitledPanel2.getContentContainer());
        jXTitledPanel2.getContentContainer().setLayout(jXTitledPanel2Layout);
        jXTitledPanel2Layout.setHorizontalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXBusyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXTitledPanel2Layout.setVerticalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXList1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jXList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jXList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jXList1);

        jXTitledPanel8.setOpaque(true);
        jXTitledPanel8.setTitle(" Бокс 3");
        jXTitledPanel8.setTitleFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jXBusyLabel25.setBusy(true);
        jXBusyLabel25.setText("Сумма");

        jXBusyLabel26.setBusy(true);
        jXBusyLabel26.setText("Класс автомобиля");

        jXBusyLabel27.setBusy(true);
        jXBusyLabel27.setText("Номер автомобиля");

        jXLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel16.setText("Пусто");

        jXLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel18.setText("Пусто");

        jXLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel17.setText("Пусто");

        jXButton9.setText("Оплатить/Сделать заказ");
        jXButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel8Layout = new javax.swing.GroupLayout(jXTitledPanel8.getContentContainer());
        jXTitledPanel8.getContentContainer().setLayout(jXTitledPanel8Layout);
        jXTitledPanel8Layout.setHorizontalGroup(
            jXTitledPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXBusyLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jXLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jXTitledPanel8Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jXButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXTitledPanel8Layout.setVerticalGroup(
            jXTitledPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jXButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jXTitledPanel7.setOpaque(true);
        jXTitledPanel7.setTitle(" Бокс 6");
        jXTitledPanel7.setTitleFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jXBusyLabel22.setBusy(true);
        jXBusyLabel22.setText("Сумма");

        jXLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel19.setText("Пусто");

        jXBusyLabel23.setBusy(true);
        jXBusyLabel23.setText("Класс автомобиля");

        jXLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel20.setText("Пусто");

        jXBusyLabel24.setBusy(true);
        jXBusyLabel24.setText("Номер автомобиля");

        jXLabel21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel21.setText("Пусто");

        jXButton10.setText("Оплатить/Сделать заказ");
        jXButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel7Layout = new javax.swing.GroupLayout(jXTitledPanel7.getContentContainer());
        jXTitledPanel7.getContentContainer().setLayout(jXTitledPanel7Layout);
        jXTitledPanel7Layout.setHorizontalGroup(
            jXTitledPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXBusyLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jXTitledPanel7Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jXButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jXTitledPanel7Layout.setVerticalGroup(
            jXTitledPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jXButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jXTitledPanel5.setOpaque(true);
        jXTitledPanel5.setTitle(" Бокс 5");
        jXTitledPanel5.setTitleFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jXBusyLabel16.setBusy(true);
        jXBusyLabel16.setText("Сумма");

        jXLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel13.setText("Пусто");

        jXBusyLabel17.setBusy(true);
        jXBusyLabel17.setText("Класс автомобиля");

        jXLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel14.setText("Пусто");

        jXBusyLabel18.setBusy(true);
        jXBusyLabel18.setText("Номер автомобиля");

        jXLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        jXLabel15.setText("Пусто");

        jXButton5.setText("Оплатить/Сделать заказ");
        jXButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXTitledPanel5Layout = new javax.swing.GroupLayout(jXTitledPanel5.getContentContainer());
        jXTitledPanel5.getContentContainer().setLayout(jXTitledPanel5Layout);
        jXTitledPanel5Layout.setHorizontalGroup(
            jXTitledPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXBusyLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXBusyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jXTitledPanel5Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jXButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jXTitledPanel5Layout.setVerticalGroup(
            jXTitledPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXBusyLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu2.setText("Отчеты");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Главное меню");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTitledPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXTitledPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jXTitledPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jXTitledPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jXTitledPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXTitledPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jXTitledPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTitledPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane2, jXTitledPanel7, jXTitledPanel8});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jXTitledPanel1, jXTitledPanel4});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jXList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXList1MouseClicked
if(jXList1.getSelectedValue().equals("Бокс 1:") 
        ||jXList1.getSelectedValue().equals("Бокс 2:")
         ||jXList1.getSelectedValue().equals("Бокс 3:")
         ||jXList1.getSelectedValue().equals("Бокс 4:")
         ||jXList1.getSelectedValue().equals("Бокс 5:") 
        ||jXList1.getSelectedValue().equals("Бокс 6:")
         ||jXList1.getSelectedValue().equals("Бокс 7:")
         ||jXList1.getSelectedValue().equals("Бокс 8:") )

{
    String a = (String) jXList1.getSelectedValue();
 
  String name = a.substring(5);
   name = name.replaceAll("[^0-9]", "");
   Integer boxi=Integer.valueOf(name);
   box=boxi;
 
order r= new  order();
r.setVisible(true);}
else {
        
       
  String a = (String) jXList1.getSelectedValue();
 
  String name = a.substring(6);
   name = name.replaceAll("[^0-9]", "");
temp = name;

current_order cr= new current_order();
cr.setVisible(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jXList1MouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
     
    }//GEN-LAST:event_formMouseMoved
public void updateJTP(){
    loadBoxes();
   set_from();
   _setBusy();
        
}
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
   updateJTP();
      
    }//GEN-LAST:event_formWindowActivated

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
   loadBoxes();
        set_from();   
         _setBusy();

    }//GEN-LAST:event_formMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        if(evt.getSource()==jMenu3){
            Main_cashier c = new   Main_cashier();
            c.setVisible(true);
            dispose();      }  // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:Shift sm = new Shift();
        Report_cashier r = new Report_cashier();
        r.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        Report_cashier rc = new  Report_cashier();
        rc.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
 box=1;  
temp=jXLabel1.getText();
if(temp.equals("Пусто")){
   
order o =new order();

o.setVisible(true);
    }
else
{
    temp=jXLabel1.getText();
current_order co = new current_order();
co.setVisible(true);
}
    }//GEN-LAST:event_jXButton1ActionPerformed

    private void jXButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton2ActionPerformed
       box=2;
        temp=jXLabel4.getText();
if(temp.equals("Пусто")){
order o =new order();

o.setVisible(true);
    }
else
{
    temp=jXLabel4.getText();
current_order co = new current_order();
co.setVisible(true);
}
    }//GEN-LAST:event_jXButton2ActionPerformed

    private void jXButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton5ActionPerformed
        box=5;
 
        temp=jXLabel13.getText();
if(temp.equals("Пусто")){
order o =new order();
o.setVisible(true);
    }
else
{
    temp=jXLabel13.getText();
current_order co = new current_order();
co.setVisible(true);
}
    }//GEN-LAST:event_jXButton5ActionPerformed

    private void jXButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton6ActionPerformed
        box=8;

        temp=jXLabel22.getText();
if(temp.equals("Пусто")){
order o =new order();
o.setVisible(true);
    }
else
{
    temp=jXLabel22.getText();
current_order co = new current_order();
co.setVisible(true);
}
    }//GEN-LAST:event_jXButton6ActionPerformed

    private void jXButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton7ActionPerformed
        box=4;
        temp=jXLabel10.getText();
if(temp.equals("Пусто")){
order o =new order();

o.setVisible(true);
    }
else
{
    temp=jXLabel10.getText();
current_order co = new current_order();
co.setVisible(true);
}
    }//GEN-LAST:event_jXButton7ActionPerformed

    private void jXButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton8ActionPerformed
        box=7;
    
        temp=jXLabel7.getText();
if(temp.equals("Пусто")){
order o =new order();
o.setVisible(true);
    }
else
{
    temp=jXLabel7.getText();
current_order co = new current_order();
co.setVisible(true);
}
    }//GEN-LAST:event_jXButton8ActionPerformed

    private void jXButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton9ActionPerformed
             box=3;
             temp=jXLabel16.getText();
if(temp.equals("Пусто")){
order o =new order();

o.setVisible(true);

    }
else
{
    temp=jXLabel16.getText();
current_order co = new current_order();
co.setVisible(true);
}
    }//GEN-LAST:event_jXButton9ActionPerformed

    private void jXButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton10ActionPerformed
temp=jXLabel19.getText();
if(temp.equals("Пусто")){
order o =new order();
box=6;
o.setVisible(true);
    }
else
{
    temp=jXLabel19.getText();
current_order co = new current_order();
co.setVisible(true);
jXTitledPanel7.repaint();
}
    }//GEN-LAST:event_jXButton10ActionPerformed
  public void set_from() {
 try {
   
        String sql="Select Car_number from autoclean_v1.order where Box='1' and Payed='Нет'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        jXLabel1.setText("Пусто");
        if(rs.next()){
          String   s1 =rs.getString("Car_number");
          jXLabel1.setText(s1);
        }
         String sql2="Select Klass_of_car from autoclean_v1.order where Box='1' and Payed='Нет'";
        pst=conn.prepareStatement(sql2);
        rs=pst.executeQuery();
        jXLabel2.setText("Пусто");
        if(rs.next()){
          String   s2 =rs.getString("Klass_of_car");
          jXLabel2.setText(s2);
        }
        String sql3="Select Summa from autoclean_v1.order where Box='1' and Payed='Нет'";
        pst=conn.prepareStatement(sql3);
        rs=pst.executeQuery();
        jXLabel3.setText("Пусто");
        if(rs.next()){
          String   s3 =rs.getString("Summa");
          jXLabel3.setText(s3);
        }
        String sql4="Select Car_number from autoclean_v1.order where Box='2' and Payed='Нет'";
        pst=conn.prepareStatement(sql4);
        rs=pst.executeQuery();
        jXLabel4.setText("Пусто");
        if(rs.next()){
          String   s4 =rs.getString("Car_number");
          jXLabel4.setText(s4);
        }
         String sql5="Select Klass_of_car from autoclean_v1.order where Box='2' and Payed='Нет'";
        pst=conn.prepareStatement(sql5);
        rs=pst.executeQuery();
        jXLabel5.setText("Пусто");
        if(rs.next()){
          String   s5 =rs.getString("Klass_of_car");
          jXLabel5.setText(s5);
        }
        String sql6="Select Summa from autoclean_v1.order where Box='2' and Payed='Нет'";
        pst=conn.prepareStatement(sql6);
        rs=pst.executeQuery();
        jXLabel6.setText("Пусто");
        if(rs.next()){
          String   s6 =rs.getString("Summa");
          jXLabel6.setText(s6);
        }
          String sql7="Select Car_number from autoclean_v1.order where Box='3' and Payed='Нет'";
        pst=conn.prepareStatement(sql7);
        jXLabel16.setText("Пусто");
        rs=pst.executeQuery();
        if(rs.next()){
          String s7 =rs.getString("Car_number");
          jXLabel16.setText(s7);
        }  String sql8="Select Klass_of_car from autoclean_v1.order where Box='3' and Payed='Нет'";
        pst=conn.prepareStatement(sql8);
        rs=pst.executeQuery();
        jXLabel18.setText("Пусто");
        if(rs.next()){
          String   s8 =rs.getString("Klass_of_car");
          jXLabel18.setText(s8);
        }  String sql9="Select Summa from autoclean_v1.order where Box='3' and Payed='Нет'";
        pst=conn.prepareStatement(sql9);
        rs=pst.executeQuery();
        jXLabel17.setText("Пусто");
        if(rs.next()){
          String   s9 =rs.getString("Summa");
          jXLabel17.setText(s9);
        }
        String sql10="Select Car_number from autoclean_v1.order where Box='4' and Payed='Нет'";
        pst=conn.prepareStatement(sql10);
        rs=pst.executeQuery();
        jXLabel10.setText("Пусто");
        if(rs.next()){
          String   s10 =rs.getString("Car_number");
          jXLabel10.setText(s10);
        }  String sql11="Select Klass_of_car from autoclean_v1.order where Box='4' and Payed='Нет'";
        pst=conn.prepareStatement(sql11);
        rs=pst.executeQuery();
        jXLabel12.setText("Пусто");
        if(rs.next()){
          String   s11 =rs.getString("Klass_of_car");
          jXLabel12.setText(s11);
        }  String sql12="Select Summa from autoclean_v1.order where Box='4' and Payed='Нет'";
        pst=conn.prepareStatement(sql12);
        rs=pst.executeQuery();
        jXLabel11.setText("Пусто");
        if(rs.next()){
          String   s12 =rs.getString("Summa");
          jXLabel11.setText(s12);
        }
        String sql13="Select Car_number from autoclean_v1.order where Box='5' and Payed='Нет'";
        pst=conn.prepareStatement(sql13);
        rs=pst.executeQuery();
        jXLabel13.setText("Пусто");
        if(rs.next()){
          String   s13 =rs.getString("Car_number");
          jXLabel13.setText(s13);
        }  String sql14="Select Klass_of_car from autoclean_v1.order where Box='5' and Payed='Нет'";
        pst=conn.prepareStatement(sql14);
        rs=pst.executeQuery();
        jXLabel15.setText("Пусто");
        if(rs.next()){
          String   s14 =rs.getString("Klass_of_car");
          jXLabel15.setText(s14);
        }  String sql15="Select Summa from autoclean_v1.order where Box='5' and Payed='Нет'";
        pst=conn.prepareStatement(sql15);
        rs=pst.executeQuery();
        jXLabel14.setText("Пусто");
        if(rs.next()){
          String   s15 =rs.getString("Summa");
          jXLabel14.setText(s15);
        }
        String sql16="Select Car_number from autoclean_v1.order where Box='6' and Payed='Нет'";
        pst=conn.prepareStatement(sql16);
        rs=pst.executeQuery();
        jXLabel19.setText("Пусто");
        if(rs.next()){
          String   s16 =rs.getString("Car_number");
          jXLabel19.setText(s16);
        }  String sql17="Select Klass_of_car from autoclean_v1.order where Box='6' and Payed='Нет'";
        pst=conn.prepareStatement(sql17);
        rs=pst.executeQuery();
        jXLabel21.setText("Пусто");
        if(rs.next()){
          String   s17 =rs.getString("Klass_of_car");
          jXLabel21.setText(s17);
        }  String sql18="Select Summa from autoclean_v1.order where Box='6' and Payed='Нет'";
        pst=conn.prepareStatement(sql18);
        rs=pst.executeQuery();
        jXLabel20.setText("Пусто");
        if(rs.next()){
          String   s18 =rs.getString("Summa");
          jXLabel20.setText(s18);
        }
        String sql19="Select Car_number from autoclean_v1.order where Box='7' and Payed='Нет'";
        pst=conn.prepareStatement(sql19);
        rs=pst.executeQuery();
        jXLabel7.setText("Пусто");
        if(rs.next()){
          String   s19 =rs.getString("Car_number");
          jXLabel7.setText(s19);
        }  String sql20="Select Klass_of_car from autoclean_v1.order where Box='7' and Payed='Нет'";
        pst=conn.prepareStatement(sql20);
        rs=pst.executeQuery();
        jXLabel9.setText("Пусто");
        if(rs.next()){
          String   s20 =rs.getString("Klass_of_car");
          jXLabel9.setText(s20);
        }  String sql21="Select Summa from autoclean_v1.order where Box='7' and Payed='Нет'";
        pst=conn.prepareStatement(sql21);
        rs=pst.executeQuery();
        jXLabel8.setText("Пусто");
        if(rs.next()){
          String   s21 =rs.getString("Summa");
          jXLabel8.setText(s21);
        }
        String sql22="Select Car_number from autoclean_v1.order where Box='8' and Payed='Нет'";
        pst=conn.prepareStatement(sql22);
        rs=pst.executeQuery();
        jXLabel22.setText("Пусто");
        if(rs.next()){
          String   s22 =rs.getString("Car_number");
          jXLabel22.setText(s22);
        }  String sql23="Select Klass_of_car from autoclean_v1.order where Box='8' and Payed='Нет'";
        pst=conn.prepareStatement(sql23);
        rs=pst.executeQuery();
        jXLabel24.setText("Пусто");
        if(rs.next()){
          String   s23 =rs.getString("Klass_of_car");
          jXLabel24.setText(s23);
        }  String sql24="Select Summa from autoclean_v1.order where Box='8' and Payed='Нет'";
        pst=conn.prepareStatement(sql24);
        rs=pst.executeQuery();
        jXLabel23.setText("Пусто");
        if(rs.next()){
          String   s24=rs.getString("Summa");
          jXLabel23.setText(s24);
        }
         
      
       _setBusy();
    } catch (SQLException ex) {
        Logger.getLogger(new_order.class.getName()).log(Level.SEVERE, null, ex);
    }    }
    
    public void _setBusy(){
         
     if(jXLabel1.getText().equals("Пусто")){
        jXBusyLabel1.setBusy(true);
        jXBusyLabel2.setBusy(true);
        jXBusyLabel3.setBusy(true);
                }
        else{
         jXBusyLabel1.setBusy(false);
                jXBusyLabel2.setBusy(false); 
                jXBusyLabel3.setBusy(false);
                }
      if(jXLabel4.getText().equals("Пусто")){
        jXBusyLabel7.setBusy(true);
        jXBusyLabel8.setBusy(true);
        jXBusyLabel9.setBusy(true);
        
        }
        else{
         jXBusyLabel7.setBusy(false);
                jXBusyLabel8.setBusy(false); 
                jXBusyLabel9.setBusy(false);
                }
       if(jXLabel9.getText().equals("Пусто")){
        jXBusyLabel24.setBusy(true);
        jXBusyLabel23.setBusy(true);
        jXBusyLabel22.setBusy(true);
        
        }
        else{
         jXBusyLabel24.setBusy(false);
                jXBusyLabel23.setBusy(false); 
                jXBusyLabel22.setBusy(false);
                }
       if(jXLabel10.getText().equals("Пусто")){
        jXBusyLabel15.setBusy(true);
        jXBusyLabel14.setBusy(true);
        jXBusyLabel13.setBusy(true);
        
        }
        else{
         jXBusyLabel15.setBusy(false);
                jXBusyLabel14.setBusy(false); 
                jXBusyLabel13.setBusy(false);
                }
       if(jXLabel13.getText().equals("Пусто")){
        jXBusyLabel18.setBusy(true);
        jXBusyLabel17.setBusy(true);
        jXBusyLabel16.setBusy(true);
        
        }
        else{
         jXBusyLabel18.setBusy(false);
                jXBusyLabel17.setBusy(false); 
                jXBusyLabel16.setBusy(false);
                }
       if(jXLabel16.getText().equals("Пусто")){
        jXBusyLabel27.setBusy(true);
        jXBusyLabel26.setBusy(true);
        jXBusyLabel25.setBusy(true);
        
        }
        else{
         jXBusyLabel27.setBusy(false);
                jXBusyLabel26.setBusy(false); 
                jXBusyLabel25.setBusy(false);
                }
       if(jXLabel7.getText().equals("Пусто")){
        jXBusyLabel12.setBusy(true);
        jXBusyLabel11.setBusy(true);
        jXBusyLabel10.setBusy(true);
        
        }
        else{
         jXBusyLabel12.setBusy(false);
                jXBusyLabel11.setBusy(false); 
                jXBusyLabel10.setBusy(false);
                }
       if(jXLabel22.getText().equals("Пусто")){
        jXBusyLabel21.setBusy(true);
        jXBusyLabel20.setBusy(true);
        jXBusyLabel19.setBusy(true);
        
        }
        else{
         jXBusyLabel21.setBusy(false);
                jXBusyLabel20.setBusy(false); 
                jXBusyLabel19.setBusy(false);
                }
             

    }
   public void loadBoxes()
    { 
    
        try{
            int Max=8;
           
            String[] Boxes = new String[Max];
            for (int i = 0; i < Max; i++)
            {
                Boxes[i] = "Бокс "+(i+1)+":";
                System.out.println(Boxes[i]+" \n");
            }
            
        for (int i=1;i<=Max;i++){
            String sql1 ="select Car_number from autoclean_v1.order where Box='"+i+"' and Payed='Нет'";
            //System.out.println(sql1);
            pst =conn.prepareStatement(sql1);
            rs=pst.executeQuery();
            while(rs.next()){
                Integer  Car_number = rs.getInt("Car_number");System.out.println(Car_number+" \n");
                    Boxes[i-1]=Boxes[i-1]+ "Машина №" +Car_number;
            }
        }     
        DefaultComboBoxModel myModel = new DefaultComboBoxModel(Boxes);
        jXList1.setModel(myModel);      
        }
             catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }    // TODO add your handling code here:
         
        
            
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_order().setVisible(true);
            }
        });
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel1;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel10;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel11;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel12;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel13;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel14;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel15;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel16;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel17;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel18;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel19;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel2;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel20;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel21;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel22;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel23;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel24;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel25;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel26;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel27;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel3;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel7;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel8;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel9;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton10;
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXButton jXButton5;
    private org.jdesktop.swingx.JXButton jXButton6;
    private org.jdesktop.swingx.JXButton jXButton7;
    private org.jdesktop.swingx.JXButton jXButton8;
    private org.jdesktop.swingx.JXButton jXButton9;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel10;
    private org.jdesktop.swingx.JXLabel jXLabel11;
    private org.jdesktop.swingx.JXLabel jXLabel12;
    private org.jdesktop.swingx.JXLabel jXLabel13;
    private org.jdesktop.swingx.JXLabel jXLabel14;
    private org.jdesktop.swingx.JXLabel jXLabel15;
    private org.jdesktop.swingx.JXLabel jXLabel16;
    private org.jdesktop.swingx.JXLabel jXLabel17;
    private org.jdesktop.swingx.JXLabel jXLabel18;
    private org.jdesktop.swingx.JXLabel jXLabel19;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXLabel jXLabel20;
    private org.jdesktop.swingx.JXLabel jXLabel21;
    private org.jdesktop.swingx.JXLabel jXLabel22;
    private org.jdesktop.swingx.JXLabel jXLabel23;
    private org.jdesktop.swingx.JXLabel jXLabel24;
    private org.jdesktop.swingx.JXLabel jXLabel3;
    private org.jdesktop.swingx.JXLabel jXLabel4;
    private org.jdesktop.swingx.JXLabel jXLabel5;
    private org.jdesktop.swingx.JXLabel jXLabel6;
    private org.jdesktop.swingx.JXLabel jXLabel7;
    private org.jdesktop.swingx.JXLabel jXLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel9;
    private org.jdesktop.swingx.JXList jXList1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel2;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel3;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel4;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel5;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel6;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel7;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel8;
    // End of variables declaration//GEN-END:variables

  
}
