/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test.auto;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Алексей
 */
public class order extends javax.swing.JFrame {
   
Connection conn = null;
ResultSet rs = null;

PreparedStatement pst = null;
public String gen_ser=" ";
public String sec_ser=null;
public double sec_sum = 0;
public double sum = 0;
public String kind_car;
public String cashier;
public String admin;
public int sixth=0;
   public int shift;
   public String shifts, worker1, worker2;
   public String shiftsall;
  public String six;
    /**
     * Creates new form order
     */
    public order() {
        initComponents();
   
         conn = javaconnect.ConnecrDb();
         kind_car=(String)_kind_of_car.getSelectedItem();  
      
         get_users_sys();
        loadBoxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _nomer_auto = new javax.swing.JTextField();
        _kind_of_car = new javax.swing.JComboBox();
        _discount = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        _kind_of_pay = new javax.swing.JComboBox();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jXComboBox1 = new org.jdesktop.swingx.JXComboBox();
        jXComboBox2 = new org.jdesktop.swingx.JXComboBox();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jXBusyLabel1 = new org.jdesktop.swingx.JXBusyLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jXPanel3 = new org.jdesktop.swingx.JXPanel();
        jButton19 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        _exit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        jXPanel2 = new org.jdesktop.swingx.JXPanel();
        jXLabel2 = new org.jdesktop.swingx.JXLabel();
        _services_name = new org.jdesktop.swingx.JXLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        _report = new javax.swing.JMenu();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

        jLabel8.setText("Услуги");

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        jLabel7.setText("Клас автомобиля");

        jLabel5.setText("Скидка");

        _kind_of_car.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Стандарт", "C-класс", "Джип", "Микроавтобус" }));
        _kind_of_car.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                _kind_of_carPopupMenuCanceled(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                _kind_of_carPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        _kind_of_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _kind_of_carActionPerformed(evt);
            }
        });

        _discount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "5", "10", "20", "100" }));

        jLabel4.setText("Тип расчета");

        jLabel1.setText("Номерной знак автомобиля");

        _kind_of_pay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Нал", "Безнал", "Чек" }));

        jXButton1.setText("Проверить номер");
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCheckBox1.setText("6-мойка");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        jXLabel1.setText("Бригада");

        jXComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jXComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jXComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXComboBox1ActionPerformed(evt);
            }
        });

        jXComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jXComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_kind_of_car, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(_nomer_auto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_kind_of_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jXComboBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_nomer_auto)
                            .addComponent(jXButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_kind_of_car, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_kind_of_pay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jXComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jXLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        jXPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

        jXBusyLabel1.setText("Информация по автомобилю");

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jXTable1);

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXBusyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jXBusyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));

        jButton19.setText("Мойка колес(с диск)");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton1.setText("Кузов");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Пластик");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton12.setText("Воск");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton17.setText("Натер ковр силик");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton20.setText("Консерв колес(силик)");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton15.setText("Замки");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton31.setText("Экспресс");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton18.setText("Мойка колес(без дис)");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton14.setText("Резинки");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton22.setText("Продув ковр");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton16.setText("Багажник");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton13.setText("Днище");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton6.setText("Двигатель");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton10.setText("Вытереть диски(внутр)");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton8.setText("Кожа");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton11.setText("Салон");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton9.setText("Пылесос");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton21.setText("Коврик");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton3.setText("Х/Ч ковриков");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Полировка кузова");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Стирка ковриков");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/auto/1455499488_services.png"))); // NOI18N
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton26.setText("Колеса");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel3Layout = new javax.swing.GroupLayout(jXPanel3);
        jXPanel3.setLayout(jXPanel3Layout);
        jXPanel3Layout.setHorizontalGroup(
            jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel3Layout.createSequentialGroup()
                        .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jXPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jButton17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jButton20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jXPanel3Layout.setVerticalGroup(
            jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel3Layout.createSequentialGroup()
                            .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel3Layout.createSequentialGroup()
                                    .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(86, 86, 86))
                                .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel3Layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(362, 362, 362)))
                    .addGroup(jXPanel3Layout.createSequentialGroup()
                        .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jXPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jXPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton10, jButton11, jButton12, jButton13, jButton15, jButton16, jButton17, jButton18, jButton19, jButton20, jButton21, jButton22, jButton24, jButton26, jButton3, jButton31, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jXPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jXPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(347, 347, 347))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

        _exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/auto/1455114901_Log Out.png"))); // NOI18N
        _exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _exitActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/auto/1455114702_Complete_Symbol.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jXButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/auto/1455247082_DeleteRed.png"))); // NOI18N
        jXButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jXPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));

        jXLabel2.setText("Выбранные услуги");

        javax.swing.GroupLayout jXPanel2Layout = new javax.swing.GroupLayout(jXPanel2);
        jXPanel2.setLayout(jXPanel2Layout);
        jXPanel2Layout.setHorizontalGroup(
            jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel2Layout.createSequentialGroup()
                .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_services_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jXPanel2Layout.setVerticalGroup(
            jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel2Layout.createSequentialGroup()
                .addGroup(jXPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(_services_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jXPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jXLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu6.setText("Отчеты по заказам");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu3.setText("Главное меню");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        _report.setText("Отчет по сменам");
        _report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _reportMouseClicked(evt);
            }
        });
        jMenuBar1.add(_report);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jXPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void cashier(){

}
public void loadBoxes()
    { 
    
        try{
            int Max=9;
           
            String[] Boxes = new String[Max];
           
            
        for (int i=1;i<=Max;i++){
            String sql1 ="select worker from autoclean_v1.worker where id='"+i+"'";
            //System.out.println(sql1);
            pst =conn.prepareStatement(sql1);
            rs=pst.executeQuery();
            while(rs.next()){
                String  worker = rs.getString("worker");System.out.println(worker+" \n");
                    Boxes[i]=worker;
            }
        }     
        DefaultComboBoxModel myModel = new DefaultComboBoxModel(Boxes);
         DefaultComboBoxModel myModel2 = new DefaultComboBoxModel(Boxes);
        jXComboBox1.setModel(myModel);      
        jXComboBox2.setModel(myModel2);      
        }
             catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }    // TODO add your handling code here:
         
        
            
    }
 public void get_users_sys(){
    try {
        String sqlc="select user_of_sys.Second_first_name from user_of_sys "
                + "where id=(select max(id)-1 from user_of_sys)";
        pst=conn.prepareStatement(sqlc);
        rs=pst.executeQuery();
        if(rs.next()){
        cashier=rs.getString("Second_first_name");}
        String sqla="select user_of_sys.Second_first_name from user_of_sys "
                + "where id=(select max(id) from user_of_sys)";
        pst=conn.prepareStatement(sqla);
        rs=pst.executeQuery();
        if(rs.next()){
        admin=rs.getString("Second_first_name");}
        
        JOptionPane.showMessageDialog(rootPane, cashier+""+admin);
    } catch (SQLException ex) {
        Logger.getLogger(order.class.getName()).log(Level.SEVERE, null, ex);
    }
 
 }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(jCheckBox1.isSelected())
 six="6 мойка";


        String discounts=(String)_discount.getSelectedItem();      
    int discount =Integer.valueOf(discounts);
     sum=sum+sec_sum;
  sum=sum*(1-(discount/100.0));
  sum=Math.ceil(sum);
 JOptionPane.showMessageDialog(rootPane, "К оплате "+sum, "Подтверждение заказа", 1);
   DateFormat format = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss zzz", Locale.US);
  Timestamp dt=Timestamp.valueOf(LocalDateTime.now());
 

                 



int p =  JOptionPane.showConfirmDialog(rootPane, "Были выбраны следующие основные услуги"
        + "\n"+gen_ser+""+"Дополнительные услуги \n "+sec_ser, "Подтвердите пожалуйста заказ"
                + " \n", JOptionPane.NO_OPTION);
if(p==0){
        try{
String nomer_auto = _nomer_auto.getText();
   Integer car_numb=Integer.valueOf(nomer_auto);

 
   
    Integer box=new_order.box;
 
          


        String sql = "INSERT INTO autoclean_v1.order (Order_dates, Order_times, Car_number, Klass_of_car,"
                + " Kind_of_service, Second_of_service, Summa, Kind_payed, Shift, Discount, Cashier, Admin, Box, Payed, Additional) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, '"+shifts+"', '"+discount+"',  '"+cashier+"', "
                + "'"+admin+"','"+box+"', 'Нет', '"+six+"');";
        pst =conn.prepareStatement(sql);
        pst.setTimestamp(1, dt);
          pst.setTimestamp(2, dt);
          pst.setInt(3, car_numb);
          pst.setString(4, kind_car);
          pst.setString(5, gen_ser);
          pst.setString(6, sec_ser);
          if(_kind_of_pay.getSelectedIndex()==0){
              
          pst.setDouble(7, sum);
                    pst.setString(8, "Нал");

          }
          if(_kind_of_pay.getSelectedIndex()==1)
          {
          pst.setDouble(7, sum);
          pst.setString(8, "Без. нал");
          }
          if(_kind_of_pay.getSelectedIndex()==2)
          {
          pst.setDouble(7, sum);
          pst.setString(8, "Чек");
          }
        if(_discount.getSelectedIndex()==5){
                      pst.setDouble(7, sum);

          pst.setString(8, "Бесплатно");
        }
              
                     pst.executeUpdate();
        new_order no = new new_order(); 
        no.loadBoxes();
no.set_from();
no._setBusy();
no.repaint();
dispose();
        sum=0;
        _nomer_auto.setText("");
        sec_ser="";
        sec_sum=0;
        gen_ser=" ";
        sec_ser=null;
        sum=0;
        
                        

        }
 catch( NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }   }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void _exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__exitActionPerformed
if(evt.getSource()==_exit){
           new_order m = new   new_order();
              m.setVisible(true);
              dispose();      }          // TODO add your handling code here:
    }//GEN-LAST:event__exitActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
Main_cashier mc = new   Main_cashier();
            mc.setVisible(true);
            dispose();          
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
  
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:Shift sm = new Shift();
        Report_cashier rcs = new  Report_cashier();
        rcs.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void _reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__reportMouseClicked
        if(evt.getSource()==_report){
            report_od_day r = new   report_od_day();
            r.setVisible(true);
            dispose();      } // TODO add your handling code here:
    }//GEN-LAST:event__reportMouseClicked

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        try {
            String string_car_number=_nomer_auto.getText();
            Integer temp_car_numb=Integer.valueOf(string_car_number);
            String sql="select Car_number As Автомобиль , count(Car_number) As Количество_заездов from autoclean_v1.`order` where Car_number='"+string_car_number+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            jXTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(order.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXButton1ActionPerformed

    private void _kind_of_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__kind_of_carActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__kind_of_carActionPerformed

    private void _kind_of_carPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event__kind_of_carPopupMenuWillBecomeInvisible
        kind_car=(String)_kind_of_car.getSelectedItem();
        // TODO add your handling code here:
    }//GEN-LAST:event__kind_of_carPopupMenuWillBecomeInvisible

    private void _kind_of_carPopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event__kind_of_carPopupMenuCanceled

        // TODO add your handling code here:
    }//GEN-LAST:event__kind_of_carPopupMenuCanceled

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try       {
            String sql ="select Service from service where 'Багажник'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Багажник'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try       {
            String sql ="select Service from service where 'Двигатель'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Двигатель'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        try       {
            String sql ="select Service from service where 'Коврик'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Коврик'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed

        sec_ser = JOptionPane.showInputDialog(rootPane, "Пожалуйста, названия доп услуг", "Допoлнительные услуги", 3);

        String sec_sum_s = JOptionPane.showInputDialog(rootPane, "Пожалуйста, введите сумму к оплате за доп услуги", "Доплонительные услуги",  3);

        sec_sum=Double.valueOf(sec_sum_s);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        try       {
            String sql ="select Service from service where 'Продувка коврика'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Продувка коврика'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

        try       {
            String sql ="select Service from service where 'Консерв колес(силик)'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Консерв колес(силик)'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        try       {
            String sql ="select Service from service where 'Мойка колес(с диском)'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Мойка колес(с диском)'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        try       {
            String sql ="select Service from service where 'Мойка колес(без диска)'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Мойка колес(без диска)'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        try       {
            String sql ="select Service from service where 'Натереть коврик силикон.'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Натереть коврик силикон.'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        try       {
            String sql ="select Service from service where 'Экспресс'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Экспресс'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }           // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        try       {
            String sql ="select Service from service where 'Колеса'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Колеса'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }           // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try       {
            String sql ="select Service from service where 'Салон'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Салон'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try       {
            String sql ="select Service from service where 'Кузов'=Service and '"+kind_car+"'= Kind_of_car ;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";
                _services_name.setText(gen_ser);
                ;
                System.out.println(gen_ser);

            }

            String sql2 ="select Price from service where 'Кузов'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                if(jCheckBox1.isSelected()){
                    sum=sum+0   ;
                }
                else {
                    String p1=rs.getString("Price");

                    sum=sum+Integer.valueOf(p1);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        // TOD        // TODO add your handling code here:*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try       {
            String sql ="select Service from service where 'Кожа'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Кожа'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try       {
            String sql ="select Service from service where 'Полировка кузова'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Полировка кузова'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try       {
            String sql ="select Service from service where 'Пластик'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Пластик'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try       {
            String sql ="select Service from service where 'Х/Ч ковриков'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Х/Ч ковриков'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(SQLException | HeadlessException | NumberFormatException e){
            JOptionPane.showMessageDialog(null, e);
        }           // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try       {
            String sql ="select Service from service where 'Стирка ковриков'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Стирка ковриков'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }           // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try       {
            String sql ="select Service from service where 'Замки'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Замки'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            String sql = "select Service from service where 'Резинки'=Service and '" + kind_car + "'= Kind_of_car;";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String ser1 = rs.getString("Service");
                gen_ser = gen_ser + "  " + ser1;
                ;

            }
            String sql2 = "select Price from service where 'Резинки'=Service and '" + kind_car + "'= Kind_of_car;";
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            if (rs.next()) {
                String p1 = rs.getString("Price");

                sum = sum + Integer.valueOf(p1);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try       {
            String sql ="select Service from service where 'Днище'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Днище'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try       {
            String sql ="select Service from service where 'Воск'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Воск'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try       {
            String sql ="select Service from service where 'Вытереть диски внутри'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Вытереть диски внутри'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try       {
            String sql ="select Service from service where 'Пылесос'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String ser1 = rs.getString("Service");
                gen_ser=gen_ser+ "  " +ser1 + "\n";                _services_name.setText(gen_ser);
                ;

            }
            String sql2 ="select Price from service where 'Пылесос'=Service and '"+kind_car+"'= Kind_of_car;";
            pst =conn.prepareStatement(sql2);
           rs=pst.executeQuery();
            if(rs.next()){
                String p1=rs.getString("Price");

                sum=sum+Integer.valueOf(p1);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jXComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jXComboBox1PopupMenuWillBecomeInvisible
       worker1=(String)jXComboBox1.getSelectedItem();
    }//GEN-LAST:event_jXComboBox1PopupMenuWillBecomeInvisible

    private void jXComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jXComboBox2PopupMenuWillBecomeInvisible
worker2=(String)jXComboBox2.getSelectedItem();   
shifts=worker1+" "+worker2;
    }//GEN-LAST:event_jXComboBox2PopupMenuWillBecomeInvisible

    private void jXComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXComboBox1ActionPerformed
        // TODO add your handling code here:9+++++\7
        
  
    }//GEN-LAST:event_jXComboBox1ActionPerformed

    private void jXButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new order().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox _discount;
    private javax.swing.JButton _exit;
    private javax.swing.JComboBox _kind_of_car;
    private javax.swing.JComboBox _kind_of_pay;
    private javax.swing.JTextField _nomer_auto;
    private javax.swing.JMenu _report;
    private org.jdesktop.swingx.JXLabel _services_name;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXBusyLabel jXBusyLabel1;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXComboBox jXComboBox1;
    private org.jdesktop.swingx.JXComboBox jXComboBox2;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private org.jdesktop.swingx.JXLabel jXLabel2;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private org.jdesktop.swingx.JXPanel jXPanel2;
    private org.jdesktop.swingx.JXPanel jXPanel3;
    private org.jdesktop.swingx.JXTable jXTable1;
    // End of variables declaration//GEN-END:variables
}
